# Generated by Django 4.1.2 on 2023-04-30 07:59

from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('identificador', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('codigo', models.CharField(db_index=True, max_length=255)),
                ('genero', models.CharField(choices=[('Hombre', 'hombre'), ('Mujer', 'mujer'), ('Infantil', 'infantil'), ('Unisex', 'unisex')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='main.categoria')),
            ],
            options={
                'ordering': ('nombre',),
                'index_together': {('id', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='TallaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.DecimalField(choices=[(22.0, 22.0), (22.5, 22.5), (23.0, 23.0), (23.5, 23.5), (24.0, 24.0), (24.5, 24.5), (25.0, 25.0), (25.5, 25.5), (26.0, 26.0), (26.5, 26.5), (27.0, 27.0), (27.5, 27.5), (28.0, 28.0), (28.5, 28.5), (29.0, 29.0), (29.5, 29.5), (30.0, 30.0), (30.5, 30.5), (31.0, 31.0), (31.5, 31.5), (32.0, 32.0)], decimal_places=1, max_digits=5)),
                ('stock', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=main.models.upload_location)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.producto')),
            ],
        ),
    ]
