# Generated by Django 4.1.2 on 2023-05-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritousuario',
            name='cantidad_productos',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='carritousuario',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
