# Generated by Django 4.1.2 on 2023-05-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_alter_carritousuario_cantidad_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritousuario',
            name='cantidad_productos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carritousuario',
            name='importe_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='detallecarritoproducto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallecarritoproducto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
