# Generated by Django 4.1.2 on 2023-05-05 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('shopping_cart', '0003_alter_carritousuario_cantidad_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecarritoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_carrito', to='main.producto'),
        ),
    ]
